[package]
name = "soundcard"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"

[target.'cfg(target_os = "macos")'.dependencies]
coreaudio-rs = "0.11.1"

[target.'cfg(target_os = "linux")'.dependencies]
alsa = "0.6.0"

[dev-dependencies]
wav = "1.0.0"
